include: Add a copy of qcom bt header
sometimes could happen that the build of libantradio fails due to a missing include:

external/ant-wireless/ant_native/src/bt-vendor_vfs/ant_native_chardev.c:47:10: fatal error: 'bt_vendor_qcom.h' file not found

this file is located in hardware/qcom/bt-caf/libbt-vendor/include but for some reasons the builder decide to ignore that file so we need to make a copy of it here

Signed-off-by: mj1687 <alessandro.pasini12@gmail.com>